[package]
name = "pm-view"
description = "Packing-Man CLI"
readme = "readme.md"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "pm-view"
path = "src/main.rs"

[dependencies]
pm-benchmark = { workspace = true }
pm-solver = { workspace = true }
pm-svg = { workspace = true }
pm-types = { workspace = true }
serde_json = { workspace = true }
