[package]
name = "pm-solver-gpu"
description = "Packing GPU 求解算法"
readme = "readme.md"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[features]
default = []
gpu = []

[dependencies]
pm-solver-cpu = { workspace = true }
pm-types = { workspace = true }
